version: '3.8'

services:
  postgres:
    image: postgres:15 # Use a versão desejada do PostgreSQL
    container_name: postgress_container
    ports:
      - '6543:6543' # Porta local:porta do container
    environment:
      POSTGRES_USER: postgres.dulfptftanpgjzmzcvut
      POSTGRES_PASSWORD: bzV12L6t2j6xfYHp
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
